### ISSUE TITLE
I had a problem while running the code

### ISSUE THREAD

**Issue by Xinchungeorb** [hanglearning/VBFL#2]
I had a problem while running the code：

NameError: name 'new_begining_mining_time' is not defined

Can you help me?Thanks!

**Comment by Xinchungeorb** [comment]
Traceback (most recent call last):
  File "main.py", line 673, in <module>
    begin_mining_time = new_begining_mining_time if new_begining_mining_time > begin_mining_time else begin_mining_time
NameError: name 'new_begining_mining_time' is not defined

**Comment by hanglearning** [comment]
Hi Xinchungeorb, thanks for your interest! May I know what arguments did you use to run the code so I can reproduce the execution? Thank you!

**Comment by Xinchungeorb** [comment]
I'm sorry to bother you.I think the reason may be that the ‘new_begining_mining_time’ is undefined.
THX！

**Comment by hanglearning** [comment]
Hi Xinchungeorb, not at all! I am open to discussions any time 😊 Yes the error should be caused by " ‘new_begining_mining_time’ is undefined", which means that "verification_time" at line 626 of main.py is False, meaning that it is either miner's computation power is 0 (Device.py line 908), or the validator is in miner's blacklist (Device.py line 915). However, under these two situations, I should process new_begining_mining_time specifically, so this should be a bug in my code. I apologize for the confusion.

At this time, it might be hard for me to change this code within a reasonable time as it's been a while since I wrote it. If you try the sample running command with your desirable values, the code should run without issues. Please let me know if it continues to bother you, then I will definitely fix this bug. Thanks for helping me spot this bug! 👍
