### ISSUE TITLE
POS

### ISSUE THREAD

**Issue by TLtianli** [hanglearning/VBFL#4]
In the initial stage of pos, the initial assets of all miners are 0, which will definitely lead to a fork，how to solve this please？

**Comment by hanglearning** [comment]
Hi TLtianli, thanks for your interest in our work and this is indeed a great question! In VBFL, there is no code to enforce chain resyncing when a forking event happens, but in a work I am still working on called [PoLL](https://github.com/hanglearning/POLL), which is also a PoS-based FL system with [LTH pruning](https://arxiv.org/abs/1803.03635), I solved forking by two situations. Notice that in PoLL, we have discarded miners, so there are only workers and validators, and a validator is the one to generate a block. So -

1. Whenever a device receives a block that does not match the previous hash, meaning a forking event happens, it discards its current chain and resyncs to the sending validator's chain at the beginning of the next round.
2. If situation 1 does not happen, at the beginning of each round, a device will always resync its chain to the validator in the round holding the highest stake recorded in its stake tracker. This is especially helpful when a device goes offline or out of sync with its peers for a while, meaning it has most likely missed some blocks compared to other devices. A device should always pick the highest holding validator rather than the highest holding device for three reasons - 1. this is an incentive for a device to become a validator; 2. mitigate the chance of always resyncing to a malicious chain when the highest stakeholding device is compromised (role-switching still exists in PoLL); 3. a device will always select the winning validator's block at the end of a round anyway, so resyncing to its chain first will avoid forking at the end

By enforcing these two mechanisms, our [simulation result](https://wandb.ai/hangchen/POLL_MNIST_1/runs/141p908i/logs?workspace=user-hangchen) shows that forking will always happen in the first round, but every device seems to pick the same block after 1 to 3 rounds.

As for VBFL, we can replace the validator mentioned in these two situations with VBFL's miner, and I think it will also work.

The chain resync function of PoLL can be found [here](https://github.com/hanglearning/POLL/blob/main/device.py#L103).

I apologize for not implementing this functionality in VBFL due to time constraints. I expect to publish PoLL by the end of the year. Once I have it done, I will share the paper with you. It will document the details for solving a forking event.

Thank you, and please let me know if this makes sense or is not clear.

**Comment by TLtianli** [comment]
Thank you very much for your detailed answer. The problem has been solved. I have learned a lot from the code you wrote. I hope to continue to learn more from you in the future. I hope you can publish more top conferences and look forward to your latest results. 3Q!!!

**Comment by hanglearning** [comment]
You are very welcome TLtianli! I am so happy that you could learn something although my code is so messy 😅 PoLL's code will be much cleaner and modular. Thanks for your kind words, and I will do my best! Let's definitely keep in touch and make some progress together! 加油 ✌️
